version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    working_dir: /app
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./model:/app/model
    environment:
      - MODEL_PATH=/app/model/saved_model/
