version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules   # avoid overwriting node_modules
    command: ["npm", "run", "dev"]
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./model:/app/model
    environment:
      - MODEL_PATH=/app/model
